using Microsoft.Agents.AI;

namespace Squad.Aca.Agents.MAF;

/// <summary>
/// Per-run options understood by <see cref="SquadAcaAIAgent"/>.
/// </summary>
/// <remarks>
/// Everything here is optional. A run that supplies none of it falls back to the
/// agent's <see cref="SquadAcaAgentOptions"/>, which is what makes
/// <c>agent.RunAsync("fix the flaky test")</c> work from a MAF pipeline that
/// knows nothing about repositories or sandbox classes.
/// </remarks>
public sealed class SquadAcaAgentRunOptions : AgentRunOptions
{
    /// <summary>Creates empty run options.</summary>
    public SquadAcaAgentRunOptions()
    {
    }

    /// <summary>Copy constructor, used by <see cref="Clone"/>.</summary>
    /// <param name="other">Options to copy.</param>
    public SquadAcaAgentRunOptions(SquadAcaAgentRunOptions other)
        : base(other)
    {
        ArgumentNullException.ThrowIfNull(other);
        Repository = other.Repository;
        SessionName = other.SessionName;
        Ref = other.Ref;
        OutputBranch = other.OutputBranch;
        PushChanges = other.PushChanges;
        SubSquad = other.SubSquad;
        LongRunMode = other.LongRunMode;
        RunTimeout = other.RunTimeout;
    }

    /// <summary>Target repository (<c>owner/repo</c>). Overrides the agent default.</summary>
    public string? Repository { get; set; }

    /// <summary>Stable session / pod id. Generated by the control plane when null.</summary>
    public string? SessionName { get; set; }

    /// <summary>Git ref to operate on. Overrides the agent default.</summary>
    public string? Ref { get; set; }

    /// <summary>Branch the session pushes to.</summary>
    public string? OutputBranch { get; set; }

    /// <summary>Whether the session pushes its work. Overrides the agent default.</summary>
    public bool? PushChanges { get; set; }

    /// <summary>SubSquad to activate for the session.</summary>
    public string? SubSquad { get; set; }

    /// <summary>
    /// Long-run behaviour for this run. When null the agent falls back to MAF's
    /// own <see cref="AgentRunOptions.AllowBackgroundResponses"/> protocol and
    /// then to <see cref="SquadAcaAgentOptions.DefaultLongRunMode"/>.
    /// </summary>
    public SquadLongRunMode? LongRunMode { get; set; }

    /// <summary>Overrides <see cref="SquadAcaAgentOptions.RunTimeout"/> for this run.</summary>
    public TimeSpan? RunTimeout { get; set; }

    /// <inheritdoc/>
    public override AgentRunOptions Clone() => new SquadAcaAgentRunOptions(this);
}
